apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "neo4j.fullname" . }}
  labels:
    app: {{ include "neo4j.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
