replicaCount: 1
image:
  repository: apache/kafka
  tag: "3.9"
  pullPolicy: IfNotPresent
service:
  port: 9092
replicationFactor: 3
storage:
  size: 10Gi
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
