apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "config-server.fullname" . }}-config-repo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.configRepo.storageSize }}
