input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => { "[@metadata][target_index]" => "ops-logs-%{+YYYY.MM.dd}" }
  }
}

output {
  opensearch {
    hosts => ["http://opensearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
}
